
@startuml
title 自定义角色添加
"crmRoleAuthrorityController.crmResourceDataSave()" -> "crmRoleAuthrorityController.crmResourceDataSave()" : 参数校验!
"crmRoleAuthrorityController.crmResourceDataSave()" -> "crmRoleAuthorityOptProvide.insertRole()" :
note left : 角色名称不能为空 \n主要参数 crmRoleMapper,sessionInfo

"crmRoleAuthorityOptProvide.insertRole()" -> "crmRoleService.insert()" :

"crmRoleService.insert()" -> "crmRoleService.insert()" : 参数校验\n用户登录信息校验 \n角色类型校验
note left : 参数校验 \n设置添加值
"crmRoleService.insert()" -> "crmRoleDao.insert(crmRoleMapper)" :  xml sql
"crmRoleService.insert()" -> "msgOptProvider.sendLogMessage()" : 日志保存

@enduml
