@startuml
title  前端加载自定义菜单
"PermissionController.getMemberPermission()" -> "PermissionController.getMemberPermission()" : 签名校验\n私有参数校验

"PermissionController.getMemberPermission()" -> "crmResourcesReadProvider.getByMemberIdAndVo()" : 查询会员权限数据
"crmResourcesReadProvider.getByMemberIdAndVo()" --> "PermissionController.getMemberPermission()" : List<CrmResourcesMapper> 结果集
"crmResourcesReadProvider.getByMemberIdAndVo()" -> "crmResourcesService.getByMemberIdAndVo()" :

"crmResourcesService.getByMemberIdAndVo()" --> "crmResourcesReadProvider.getByMemberIdAndVo()" : List<CrmResourcesMapper>结果集


"crmResourcesService.getByMemberIdAndVo()" -> "crmResourcesService.getByMemberIdAndVo()" : 会员信息校验

"crmResourcesService.getByMemberIdAndVo()" -> "crmResourcesDao.listBy(selectByPositionIds)" : 会员所属岗位权限信息查询\n

"crmResourcesDao.listBy(selectByPositionIds)" --> "crmResourcesService.getByMemberIdAndVo()" : List<CrmResourcesMapper>结果集

note left : 查询默认公共权限给会员\n个人主账号获取个人的权限\n子账号获取个人的权限\n附属账户获取附属账户权限\n日志保存  读取的结果集进行组装
"crmResourcesService.getByMemberIdAndVo()" -> "crmResourcesDao.selectCustomPermissionResources()" : 查询自定义角色权限

"crmResourcesDao.selectCustomPermissionResources()" --> "crmResourcesService.getByMemberIdAndVo()" : List<CrmResourcesMapper>结果集
@enduml