@startuml
title : 店铺添加类目对应自定义权限
"cmshopController.saveShopRelatingCategory()" -> "cmshopController.saveShopRelatingCategory()" :参数校验
"cmshopController.saveShopRelatingCategory()" -> "crmMemberRolesOptProvider.saveMemberRoleByShopIdAndBusinesId()" :添加自定义角色权限

note left :参数：shopId,productCategoryId \n 参数校验 \n店铺添加类目

"crmMemberRolesOptProvider.saveMemberRoleByShopIdAndBusinesId()" -> "crmMemberRoleService.saveMemberRoleByShopIdAndBusinesId()" :添加权限

"crmMemberRoleService.saveMemberRoleByShopIdAndBusinesId()" -> "crmMemberRoleService.saveMemberRoleByShopIdAndBusinesId()": 检查类目是否绑定自定义角色\n 重复添加验证\n参数校验

"crmMemberRoleService.saveMemberRoleByShopIdAndBusinesId()" -> "crmMemberRolesDao.insertBatch()" :  执行xml sql


@enduml